<Project>

  <!--
    Central Package Management.
    TODAS las versiones de NuGet viven acá. Ningún .csproj debe declarar Version="".
    Beneficio para el equipo: una sola línea a tocar para actualizar EF Core / Redis en los 4 proyectos.
  -->
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <EfCoreVersion>8.0.31</EfCoreVersion>
  </PropertyGroup>

  <ItemGroup Label="Application - Pipeline de módulos (MediatR + FluentValidation)">
    <PackageVersion Include="MediatR" Version="12.5.0" />
    <PackageVersion Include="FluentValidation" Version="12.1.1" />
    <PackageVersion Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.3" />
    <PackageVersion Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup Label="Infrastructure - Entity Framework Core">
    <PackageVersion Include="Microsoft.EntityFrameworkCore" Version="$(EfCoreVersion)" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Relational" Version="$(EfCoreVersion)" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="$(EfCoreVersion)">
      <PrivateAssets>none</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageVersion>
    <!-- Proveedor por defecto en desarrollo -->
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Sqlite" Version="$(EfCoreVersion)" />
    <!-- Proveedores productivos: se activan cambiando Database:Provider en appsettings.json -->
    <PackageVersion Include="Microsoft.EntityFrameworkCore.SqlServer" Version="$(EfCoreVersion)" />
    <PackageVersion Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.11" />
  </ItemGroup>

  <ItemGroup Label="Infrastructure - Redis / Cache distribuida">
    <PackageVersion Include="StackExchange.Redis" Version="2.13.17" />
    <PackageVersion Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="$(EfCoreVersion)" />
    <PackageVersion Include="Microsoft.Extensions.Caching.Abstractions" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup Label="Infrastructure - Salud y diagnostico">
    <PackageVersion Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" Version="$(EfCoreVersion)" />
  </ItemGroup>

  <ItemGroup Label="Api">
    <PackageVersion Include="Swashbuckle.AspNetCore" Version="8.1.4" />
    <PackageVersion Include="Asp.Versioning.Mvc" Version="8.1.1" />
    <PackageVersion Include="Asp.Versioning.Mvc.ApiExplorer" Version="8.1.1" />
    <PackageVersion Include="Serilog.AspNetCore" Version="8.0.3" />
    <PackageVersion Include="Serilog.Sinks.Console" Version="6.0.0" />
  </ItemGroup>

</Project>
